config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resource :subscriptions
  resource :card
  resource :charges
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  namespace :admin do
    root 'dashboard#index'
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :users
  end

  namespace :creators do
    root 'dashboard#index'
    get '/category_information' => 'dashboard#category_information', as: 'information'
  end

  #Stripe WebHook
  mount StripeEvent::Engine, at: '/stripe/webhook'

  #Searchkick Search
  get '/search' => 'static#search', as: 'search'
  get '/autocomplete' => 'static#autocomplete', as: 'autocomplete'

  #Stripe authentication
  get '/connect/oauth' => 'connect#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'connect#confirm', as: 'stripe_confirm'

  resources :categories, only: [:index, :show] do
    resources :snippets do
      member do
        put '/like' => 'snippets#like'
        put '/dislike' => 'snippets#dislike'
        put '/publish' => 'snippets#publish'
        put '/unpublish' => 'snippets#unpublish'
        put '/bookmark' => 'snippets#bookmark'
        put '/remove_bookmark' => 'snippets#remove_bookmark'
        put '/feature' => 'snippets#feature'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    resources :templates, except: :index do
      member do
        put '/publish' => 'templates#publish'
        put '/unpublish' => 'templates#unpublish'
      end
      resources :infopages, except: :index
    end
  end



  resources :categories, only: [:index, :show] do
    resources :tutorials, except: :index do
      resources :questions, shallow: true do
        resources :comments, except: :show do
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
        end
      end
      resources :infos, except: :index do
        resources :notes, shallow: true
      end
      member do
        put '/add_member' => 'tutorials#add_member'
        put '/remove_member' => 'tutorials#remove_member'
        put '/like', to: 'tutorials#like'
        put '/dislike', to: 'tutorials#dislike'
        put '/admin_remove_member', to: 'tutorials#admin_remove_member'
        put '/publish' => 'tutorials#publish'
        put '/unpublish' => 'tutorials#unpublish'
        get '/add_template' => 'tutorials#add_template'
        put '/add_this_template' => 'tutorials#add_this_template'
        put '/remove_template' => 'tutorials#remove_template'
        get '/payment' => 'tutorials#payment', as: 'payment'
        put '/buy' => 'tutorials#buy', as: 'buy'
        put '/quick_buy' => 'tutorials#quick_buy'
      end
    end
  end


  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :users, only: :show do
    resources :blogs
    member do
      put '/follow', to: 'users#follow'
      put '/unfollow', to: 'users#unfollow'
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authorize_admin!

  def index
  end


  private
  def authorize_admin!
    authenticate_user!
    if !current_user.admin
      redirect_to root_path
      flash[:danger] = 'You must be an admin to do that :)'
    end
  end
end

app/controllers/creators/dashboard_controller.rb
class Creators::DashboardController < ApplicationController

  before_action :authorize_user

  def index
    @new_creators = User.where(creator: true).last(4)
    @categories = Category.all
  end

  def category_information
    if Category.find_by(name: params[:category]).nil?
      flash[:danger] = 'The category you looked for could not be found'
    else
      @category = Category.find_by(name: params[:category])
    end
  end

  private
  def authorize_user
    authenticate_user!
    unless current_user.try(:admin) || current_user.try(:manager) || current_user.try(:creator)
      flash[:danger] = 'You are not authorized to access this page'
      redirect_to root_path
    end
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/creators/dashboard_helper.rb
module Creators::DashboardHelper

  def authors_with_category(category)
    arr = []
    category.tutorials.includes(:author).each do |tutorial|
      arr.push(tutorial.author.id)
    end
    arr.uniq.count
  end

  def total_contributors_count_in_category(category)
    count = 0
    category.tutorials.each do |tutorial|
      count = count + tutorial.contributors.count
    end
    count
  end

  def total_snippet_count_in_category_unpublished(category)
    count = 0
    category.snippets.each do |snippet|
      unless snippet.publish?
        count = count + 1
      end
    end
    count
  end

  def total_snippet_count_in_category_published(category)
    count = 0
    category.snippets.each do |snippet|
      if snippet.publish?
        count = count + 1
      end
    end
    count
  end
end

app/views/creators/dashboard/_category.html.erb
<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3 class="text-center text-info"><%= category.name %></h3>
      <hr>
      <p><%= "#{category.tutorials.where(publish: true).count} published tutorials" %></p>
      <p><%= "#{category.tutorials.where(publish: false).count} unpublished tutorials" %></p>
      <p><%= pluralize(authors_with_category(category), 'author') %></p>
      <%= link_to 'View all information', creators_information_path(category: category.name), class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/creators/dashboard/_creator.html.erb
<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h5 class="text-center text-info"><%= link_to user.name, user_path(user) %></h5>
      <hr>
      <p class="text-center">
        <%= gravatar_tag user.email, :size => 80, d: :identicon, html: {class: 'img-circle'} %>
      </p>
      <small class="pull-right">
        <%= truncate(user.description, length: 200) %>
      </small>
    </div>
  </div>
</div>

app/views/creators/dashboard/category_information.html.erb
<h2 class="text-center text-info">Category: <%= @category.name.capitalize! %></h2>
<hr>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title text-center">Stats for this category</h3>
      </div>
      <div class="panel-body">
        <p><%= pluralize(@category.templates.where(publish: true).count, 'template') %> published</p>
        <p><%= pluralize(@category.templates.where(publish: false).count, 'template') %> waiting to be published</p>
        <p><%= pluralize(total_contributors_count_in_category(@category), 'contributor') %> in this category</p>
        <p><%= pluralize(total_snippet_count_in_category_published(@category), 'snippet') %> published</p>
        <p><%= pluralize(total_snippet_count_in_category_unpublished(@category), 'snippet') %> waiting to be published</p>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Analytics</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
  </div>
</div>

<% @category.tutorials.each do |tutorial| %>
    <% unless tutorial.publish? %>
        <%= link_to tutorial.title, [@category, tutorial] %>
    <% end %>
<% end %>

app/views/creators/dashboard/index.html.erb
<h1 class="text-info text-center">Exclusive page for content creators !</h1>
<br>
<h3>Lets greet the new creators !</h3>
<div class="row">
  <%= render partial: 'creator', collection: @new_creators, as: :user %>
</div>
<h2 class="text-center text-info">Categories</h2>
<div class="row">
    <%= render partial: 'category', collection: @categories, as: :category %>
</div>

app/views/creators/dashboard/show.html.erb
<%= @category.tutorials.count %>