config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resource :subscriptions
  resource :card
  resource :charges
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  namespace :admin do
    root 'dashboard#index'
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :users
  end

  namespace :creators do
    root 'dashboard#index'
    get '/category_information' => 'dashboard#category_information', as: 'information'
  end

  #Stripe WebHook
  mount StripeEvent::Engine, at: '/stripe/webhook'

  #Searchkick Search
  get '/search' => 'static#search', as: 'search'
  get '/autocomplete' => 'static#autocomplete', as: 'autocomplete'

  #Stripe authentication
  get '/connect/oauth' => 'connect#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'connect#confirm', as: 'stripe_confirm'

  resources :categories, only: [:index, :show] do
    resources :snippets do
      member do
        put '/like' => 'snippets#like'
        put '/dislike' => 'snippets#dislike'
        put '/publish' => 'snippets#publish'
        put '/unpublish' => 'snippets#unpublish'
        put '/bookmark' => 'snippets#bookmark'
        put '/remove_bookmark' => 'snippets#remove_bookmark'
        put '/feature' => 'snippets#feature'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    resources :templates, except: :index do
      member do
        put '/publish' => 'templates#publish'
        put '/unpublish' => 'templates#unpublish'
      end
      resources :infopages, except: :index
    end
  end



  resources :categories, only: [:index, :show] do
    resources :tutorials, except: :index do
      resources :questions, shallow: true do
        resources :comments, except: :show do
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
        end
      end
      resources :infos, except: :index do
        resources :notes, shallow: true
      end
      member do
        put '/add_member' => 'tutorials#add_member'
        put '/remove_member' => 'tutorials#remove_member'
        put '/like', to: 'tutorials#like'
        put '/dislike', to: 'tutorials#dislike'
        put '/admin_remove_member', to: 'tutorials#admin_remove_member'
        put '/publish' => 'tutorials#publish'
        put '/unpublish' => 'tutorials#unpublish'
        get '/add_template' => 'tutorials#add_template'
        put '/add_this_template' => 'tutorials#add_this_template'
        put '/remove_template' => 'tutorials#remove_template'
        get '/payment' => 'tutorials#payment', as: 'payment'
        put '/buy' => 'tutorials#buy', as: 'buy'
        put '/quick_buy' => 'tutorials#quick_buy'
      end
    end
  end


  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :users, only: :show do
    resources :blogs
    member do
      put '/follow', to: 'users#follow'
      put '/unfollow', to: 'users#unfollow'
    end
  end
end

app/models/tutorial.rb
# == Schema Information
#
# Table name: tutorials
#
#  id                :integer          not null, primary key
#  category_id       :integer
#  title             :string
#  description       :text
#  points_covered    :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#  link_to_repo      :string
#  slug              :string
#  author_id         :integer
#  publish           :boolean          default("false")
#  template_id       :integer
#  impressions_count :integer          default("0")
#  price             :integer          default("0")
#  published         :boolean          default("false")
#

class Tutorial < ActiveRecord::Base
  markable_as :favorite
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  searchkick text_start: ['title^10', :description, :points_covered]

  def slug_candidates
    [:id, :title]
  end

  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :contributors, dependent: :destroy
  has_many :members, through: :contributors, dependent: :destroy
  has_many :infos, dependent: :delete_all
  has_many :purchases, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :snippets, dependent: :nullify

  validates :title, :description, :points_covered, presence: true


end

app/controllers/tutorials_controller.rb
# == Schema Information
#
# Table name: tutorials
#
#  id                :integer          not null, primary key
#  category_id       :integer
#  title             :string
#  description       :text
#  points_covered    :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#  link_to_repo      :string
#  slug              :string
#  author_id         :integer
#  publish           :boolean          default(FALSE)
#  template_id       :integer
#  impressions_count :integer          default(0)
#

class TutorialsController < ApplicationController

  APPLICATION_FEE = 0.3
  before_action :set_category
  before_action :set_tutorial, only: [:show, :edit, :update,
                                      :destroy, :add_member,
                                      :remove_member, :like,
                                      :dislike, :admin_remove_member, :publish,
                                      :unpublish, :add_template, :add_this_template,
                                      :remove_template, :buy, :quick_buy, :payment]
  before_action :authenticate_user!, except: :show
  before_action :set_application_fee, only: [:buy, :quick_buy]

  def new
    @tutorial = Tutorial.new
    @@template = params[:template].to_i || nil
    authorize @tutorial, :create?
  end

  def create
    @tutorial = @category.tutorials.create(tutorial_params)
    authorize @tutorial, :create?
    @tutorial.update(author: current_user)
    if Template.find_by_id @@template != nil
      @tutorial.template_id = @@template
    end
    #Contributor.create!(tutorial: @tutorial, access: true, member: current_user)
    if @tutorial.save
      flash[:success] = 'Tutorial has been created successfully'
      redirect_to category_tutorial_path(@category, @tutorial)
    else
      flash.now[:danger] = 'Template has not been created'
      render :new
    end
  end

  def show
    authorize @tutorial, :show?
    @infos = @tutorial.infos.order('created_at ASC').all
    @template = Template.find_by_id @tutorial.template_id
  end

  def edit
    authorize @tutorial, :update?
  end

  def update
    authorize @tutorial, :update?
    if @tutorial.update(tutorial_params)
      flash[:success] = 'Tutorial has been updated successfully'
      redirect_to category_tutorial_path(@category, @tutorial)
    else
      flash.now[:danger] = 'Tutorial has not been updated'
      render :edit
    end
  end

  def destroy
    authorize @tutorial, :destroy?
    @tutorial.destroy
    redirect_to root_path
    flash[:success] = 'Tutorial has been successfully deleted'
  end

  def publish
    @tutorial.update_attributes(publish: true, published: true)
    redirect_to category_tutorial_path(@category, @tutorial, anchor: 'mini-tutorial-dashboard')
  end

  def unpublish
    @tutorial.update(publish: false)
    redirect_to category_tutorial_path(@category, @tutorial, anchor: 'mini-tutorial-dashboard')
  end

  def add_member
    user = params[:user].to_i
    temp_user = User.find_by_id(user)
    if @tutorial.members.include? temp_user
      flash[:danger] = 'User once denied cannot be added again. Sorry.'
    else
      Contributor.create!(tutorial: @tutorial, access: true, member: temp_user)
      flash[:success] = "#{temp_user.name} been added as a contributor to the tutorial"
    end
    redirect_to category_tutorial_path(@category, @tutorial)
  end

  def remove_member
    user = params[:user].to_i
    temp_user = User.find_by_id(user)
    con = Contributor.where(tutorial: @tutorial, member: temp_user, access: true).first
    con.access = false
    con.save
    flash[:success] = 'User access has been revoked'
    redirect_to category_tutorial_path(@category, @tutorial)
  end


  def like
    current_user.favorite_tutorials << @tutorial
    flash[:success] = 'Added to bookmarks !'
    redirect_to category_tutorial_path(@category, @tutorial)
  end

  def dislike
    current_user.favorite_tutorials.delete @tutorial
    redirect_to category_tutorial_path(@category, @tutorial)
  end

  def admin_remove_member
    user = params[:user].to_i
    temp_user = User.find_by_id(user)
    @tutorial.members.delete temp_user
    flash[:success] = "User access for #{temp_user.name} has been reset"
    redirect_to category_tutorial_path(@category, @tutorial)
  end

  def add_template
    @templates = @category.templates.all
  end

  def add_this_template
    template = params[:template].to_i
    @tutorial.template_id = template
    if @tutorial.save
      flash[:success] = 'The template was added successfully'
    else
      flash[:danger] = 'Something went wrong. Contact the site moderators for help'
    end
    redirect_to category_tutorial_path(@category, @tutorial)
  end

  def remove_template
    @tutorial.template_id = nil
    @tutorial.save
    flash.now[:success] = 'Teemplate has been removed from the tutorial'
    redirect_to category_tutorial_path(@category, @tutorial)
  end

  def payment

  end

  def buy

    begin
      customer = Stripe::Customer.create(
          :email => current_user.email,
          :source  => params[:stripeToken]
      )
      charge = Stripe::Charge.create(
          :customer    => customer.id,
          :amount      => @tutorial.price * 100,
          :description => "You bought '#{@tutorial.title}' from Codersations",
          :destination => @tutorial.author.stripe_account_id,
          :currency    => @tutorial.author.currency,
          :application_fee => (APPLICATION_FEE * @tutorial.price).to_i * 100
      )
      current_user.update(
          stripe_id: customer.id,
          card_last4: params[:card_last4],
          card_exp_month: params[:card_exp_month],
          card_exp_year: params[:card_exp_year],
          card_type: params[:card_type]
      )
      current_user.purchases.create(
          name: current_user.name,
          email: current_user.email,
          amount: charge.amount,
          date: Time.zone.now.to_s,
          author_name: @tutorial.author.name,
          tutorial_name: @tutorial.title,
          card_last4: params[:card_last4],
          card_exp_month: params[:card_exp_month],
          card_exp_year: params[:card_exp_year],
          card_type: params[:card_type],
          charge_id: charge.id,
          balance_transaction: charge.balance_transaction,
          tutorial_id: @tutorial.id,
          user_id: current_user.id
      )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to payment_category_tutorial_path
    end
    flash[:success] = 'You successfully bought the tutorial'
    redirect_to [@category, @tutorial]
  end

  def quick_buy
    charge = Stripe::Charge.create(
        :customer    => current_user.stripe_id,
        :amount      => @tutorial.price * 100,
        :description => "You bought '#{@tutorial.title}' from Codersations",
        :destination => @tutorial.author.stripe_account_id,
        :currency    => @tutorial.author.currency,
        :application_fee => (APPLICATION_FEE * @tutorial.price).to_i * 100
    )


    current_user.purchases.create(
        name: current_user.name,
        email: current_user.email,
        amount: charge.amount,
        date: Time.zone.now.to_s,
        author_name: @tutorial.author.name,
        tutorial_name: @tutorial.title,
        card_last4: params[:card_last4],
        card_exp_month: params[:card_exp_month],
        card_exp_year: params[:card_exp_year],
        card_type: params[:card_type],
        charge_id: charge.id,
        balance_transaction: charge.balance_transaction,
        tutorial_id: @tutorial.id,
        user_id: current_user.id
    )
    flash[:success] = 'You successfully purchased this tutorial !'
    redirect_to [@category, @tutorial]

  end

  private
  def tutorial_params
    params.require(:tutorial).permit(:title, :description, :points_covered, :link_to_repo, :template, :price)
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

  def set_tutorial
    begin
      @tutorial = @category.tutorials.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:danger] = 'The tutorial you searched for could not be found'
      redirect_to root_path
    end
  end

  def set_application_fee
    @application_fee = (APPLICATION_FEE * @tutorial.price).to_i
  end

end

app/helpers/tutorials_helper.rb
# == Schema Information
#
# Table name: tutorials
#
#  id                :integer          not null, primary key
#  category_id       :integer
#  title             :string
#  description       :text
#  points_covered    :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :integer
#  link_to_repo      :string
#  slug              :string
#  author_id         :integer
#  publish           :boolean          default(FALSE)
#  template_id       :integer
#  impressions_count :integer          default(0)
#

module TutorialsHelper
  def has_access?(user, tutorial)
    user.try(:admin) || tutorial.author == user || tutorial.contributors.exists?(member: user, tutorial: tutorial, access: true)
  end

  #lists all the contributors except the tutorial author
  def list_contributors(contributors, tutorial)
    contributors_list = []
    contributors.each do |contributor|
      contributors_list.push User.find_by_id(contributor.member_id).name
    end
    contributors_list.delete(tutorial.author.name)
    contributors_list
  end

  def show_template_name(template,&block)
    block.call if template != nil
  end

  def has_purchased?(tutorial)
    if current_user.purchases.any?
      current_user.purchases.each do |purchase|
        if purchase.tutorial_name == tutorial.title
          return true
        end
      end
    end
    false
  end

  def hide_from_author(tutorial, &block)
    block.call if list_contributors(tutorial.contributors, tutorial).include? current_user
  end

end

app/views/tutorials/_form.html.erb
<%= simple_form_for [@category, @tutorial] do |f| %>
    <%= f.input :title, required: true, autofocus: true %>
    <%= f.input :description, required: true %>
    <%= f.input :points_covered %>
    <% if current_user.stripe_account_id?%>
        <%= f.input :price %>
    <% else %>
        <p class="text-muted">You need to register an account with Stripe and connect the Codersations
          platform for receiving payments</p>
        <%= f.input :price, disabled: true %>
    <% end %>
    <%= f.input :link_to_repo %>
    <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/tutorials/add_template.html.erb
<h1>Add a template</h1>
<% @templates.each do |template| %>
    <%= link_to template.name, category_template_path(@category, template) %>
    <%= link_to 'Add this template', add_this_template_category_tutorial_path(@category, @tutorial, template: template.id), class: 'btn btn-success btn-sm', method: :put %>
    <br>
<% end %>

app/views/tutorials/edit.html.erb
<h1>Edit tutorial</h1>
<%= render 'form' %>

app/views/tutorials/index.html.erb
<% @tutorials.each do |tutorial| %>
    <%= link_to tutorial.title, category_tutorial_path(tutorial.category, tutorial) %>
    <br>
<% end %>

<%= paginate @tutorials %>

app/views/tutorials/payment.html.erb
<% if !current_user.purchases.exists?(tutorial_id: @tutorial.id) %>
    <%= form_tag buy_category_tutorial_path, method: :put, :id=> 'payment-form' do %>
        <span class="payment-errors"></span>

        <div class="form-row">
          <label>
            <span>Card Number</span>
            <input value="4242424242424242" type="text" size="20" data-stripe="number"/>
          </label>
        </div>

        <div class="form-row">
          <label>
            <span>CVC</span>
            <input value="123" type="text" size="4" data-stripe="cvc"/>
          </label>
        </div>

        <div class="form-row">
          <label>
            <span>Expiration (MM/YYYY)</span>
            <input value="10" type="text" size="2" data-stripe="exp-month"/>
          </label>
          <span> / </span>
          <input value="2017" type="text" size="4" data-stripe="exp-year"/>
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Submit Payment &nbsp;<i class="fa fa-credit-card"></i></button>
    <% end %>
<% else %>
    <h1 class="text-center text-info">You have already purchased this tutorial</h1>
<% end %>

app/views/tutorials/show.html.erb
<% ahoy.track 'Viewed Tutorial', track: @tutorial.title %>
<div class="container-fluid">
  <div class="row-fluid">
    <h1 class="text-center text-info"><%= @tutorial.title %></h1>

    <h4 class="text-center text-info">Author -
      <%= gravatar_tag @tutorial.author.email, size: 40, d: :identicon, html: {class: 'img-circle'} %>
      <%= link_to @tutorial.author.name, user_path(@tutorial.author) %></h4>
    <% if @tutorial.contributors.any? %>
        <h4 class="text-info text-center">Contributors/Editors -
          <% count = 0 %>
          <% @tutorial.contributors.each do |contributor| %>
              <% count = count + 1 %>
              <% if count == @tutorial.contributors.count - 1 %>
                  <%= gravatar_tag contributor.member.email, size: 40, d: :identicon, html: { class: 'img-circle'} %>
                  <%= link_to contributor.member.name, user_path(contributor.member) %>,
              <% else %>
                  <%= gravatar_tag contributor.member.email, size: 40, d: :identicon, html: { class: 'img-circle'} %>
                  <%= link_to contributor.member.name, user_path(contributor.member) %>
              <% end %>
          <% end %>
        </h4>
    <% end %>
  </div>

  <% if policy(@tutorial).destroy? %>
      <hr>
      <div class="row">
        <h3 class="text-center text-info" id="mini-tutorial-dashboard">Mini Dashboard</h3>
        <div class="col-md-3">
          <p>Publish/Hide this tutorial</p>
          <% if policy(@tutorial).destroy? %>
              <% if @tutorial.publish %>
                  <%= link_to 'Hide Tutorial', unpublish_category_tutorial_path(@category, @tutorial), class: 'btn btn-danger btn-sm', method: :put%>
              <% else %>
                  <%= link_to 'Publish Tutorial', publish_category_tutorial_path(@category, @tutorial), class: 'btn btn-success btn-sm', method: :put%>
              <% end %>
          <% end %>
          <hr>
          <p>Edit tutorial information. <b>Once you publish a tutorial, you need admin permission to delete the
            tutorial.</b></p>
          <%= link_to 'Edit Tutorial', [:edit, @category, @tutorial], class: 'btn btn-success btn-sm' %>
          <% if current_user.try(:admin) || !@tutorial.published? %>
              <%= link_to 'Delete Tutorial', [@category, @tutorial], method: :delete, data: {confirm: 'Are you sure ?'}, class: 'btn btn-danger btn-sm' %>
          <% else %>
              <%= link_to 'Delete Tutorial', [@category, @tutorial], class: 'btn btn-danger btn-sm disabled' %>
          <% end %>
        </div>
        <div class="col-md-3">
          <p>References</p>
          <p>Templates :-</p>
          <% if @template == nil %>
              <%= link_to 'Add a template', add_template_category_tutorial_path(@category, @tutorial), class: 'btn btn-success btn-sm' %>
          <% else %>
              <%= show_template_name(@template) do %>
                  <%= link_to @template.name, category_template_path(@category, @template)%>
                  <%= link_to 'Replace this template', add_template_category_tutorial_path(@category, @tutorial), class: 'btn btn-success btn-sm', class: 'btn btn-success btn-sm' %>
                  <%= link_to 'Remove this template', remove_template_category_tutorial_path(@category, @tutorial), class: 'btn btn-success btn-sm', class: 'btn btn-success btn-sm', method: :put %>
              <% end %>
          <% end %>
          <hr>
          <p>Create a page</p>
          <%= link_to 'Create an info sheet', new_category_tutorial_info_path(@category, @tutorial), class: 'btn btn-primary btn-sm' %>
        </div>
        <div class="col-md-6 select-contributors">
          <% if @tutorial.contributors.any? %>
              <p class="text-center text-info">Add a contributor</p>
          <% else %>
              <p class="text-center text-info">You can only add your followers as contributors</p>
          <% end %>
          <% if @tutorial.author == current_user %>
              <hr>
              <div class="row">
                <h3>Users to add to tutorial</h3>
                <table class="table">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>People who follow you</th>
                    <th>Add or Remove</th>
                    <% if current_user.try(:admin) %>
                        <th>Revoke user access</th>
                    <% end %>
                  </tr>
                  </thead>
                  <tbody>

                  <% current_user.users_have_marked_as_follow.each do |user| %>
                      <tr>
                        <th>#</th>
                        <th><%= link_to user.email, user_path(user) %></th>
                        <% if Contributor.exists?(tutorial: @tutorial, member: user, access: true) %>
                            <th>
                              <%= link_to 'Remove member', remove_member_category_tutorial_path(@category, @tutorial, user: user), method: :put, class: 'btn btn-danger btn-sm' %>
                            </th>
                        <% else %>
                            <th>
                              <%= link_to 'Add member', add_member_category_tutorial_path(@category, @tutorial, user: user), method: :put, class: 'btn btn-success btn-sm' %>
                            </th>
                        <% end %>
                        <% if current_user.admin %>
                            <th><%= link_to 'Revoke User Access', admin_remove_member_category_tutorial_path(@category, @tutorial, user: user), method: :put, class: 'btn btn-warning btn-sm' %></th>
                        <% end %>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
          <% end %>
        </div>
      </div>
  <% end %>

  <% unless current_user == @tutorial.author %>
      <% if policy(@tutorial.infos.new).create? %>
          <hr>
          <div class="row">
            <p>As a contributor to this tutorial, you have the access to edit and create pages</p>
            <%= link_to 'Add an info sheet', new_category_tutorial_info_path(@category, @tutorial), class: 'btn btn-success' %>
          </div>
      <% end %>
      <hr>
  <% end %>

  <div class="row">
    <div class="col-md-4 text-center">
      <% if user_signed_in? %>
          <% if current_user.purchases.exists?(tutorial_id: @tutorial.id) || current_user.stripe_subscription_id? || @tutorial.author == current_user || current_user.try(:admin)%>
              <%= link_to 'Questions and Notes', category_tutorial_questions_path(@category, @tutorial) %>
          <% else %>
              <%= link_to 'Questions and Notes', subscriptions_path %>
          <% end %>
      <% else %>
          <%= link_to 'Questions and Notes', new_user_session_path %>
      <% end %>
    </div>
    <div class="col-md-4 text-center">
      <% if user_signed_in? %>
          <% if @tutorial.price > 0 %>
              <h4 class="text-primary text-warning"><%= "#{number_to_currency(@tutorial.price)}" %></h4>
              <% if !current_user.purchases.exists?(tutorial_id: @tutorial.id)  %>
                  <% if current_user.stripe_id? %>
                      <%= link_to 'Quick Buy', quick_buy_category_tutorial_path(@category, @tutorial), method: :put %>
                  <% else %>
                      <%= link_to 'Buy', payment_category_tutorial_path, method: :get %>
                  <% end %>
              <% else %>
                  <%= 'Purchased' %>
              <% end %>
          <% else %>
              <p class="text-info">Free Tutorial</p>
          <% end %>
      <% end %>
    </div>
    <div class="col-md-4 text-center">
      <% if @tutorial.marked_as_favorite? by: current_user %>
          <%= link_to 'Remove from bookmarks', dislike_category_tutorial_path(@category, @tutorial), method: :put %>
      <% else %>
          <%= link_to 'Add to bookmarks', like_category_tutorial_path(@category, @tutorial), method: :put %>
      <% end %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-6">
      <h3 class="text-center text-info">Description</h3>
      <p class="text-center"><%= @tutorial.description %></p>
      <hr>
      <h3 class="text-info text-center">Points Covered</h3>
      <p class="text-center"><%= @tutorial.points_covered %></p>
    </div>
    <div class="col-md-6">
      <h3 class="text-center text-info"> Index</h3>
      <ol class="rectangle-list">
        <% @infos.each do |info| %>
            <li><%= link_to info.title, category_tutorial_info_path(@category, @tutorial, info) %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div>