config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resource :subscriptions
  resource :card
  resource :charges
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  namespace :admin do
    root 'dashboard#index'
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :users
  end

  namespace :creators do
    root 'dashboard#index'
    get '/category_information' => 'dashboard#category_information', as: 'information'
  end

  #Stripe WebHook
  mount StripeEvent::Engine, at: '/stripe/webhook'

  #Searchkick Search
  get '/search' => 'static#search', as: 'search'
  get '/autocomplete' => 'static#autocomplete', as: 'autocomplete'

  #Stripe authentication
  get '/connect/oauth' => 'connect#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'connect#confirm', as: 'stripe_confirm'

  resources :categories, only: [:index, :show] do
    resources :snippets do
      member do
        put '/like' => 'snippets#like'
        put '/dislike' => 'snippets#dislike'
        put '/publish' => 'snippets#publish'
        put '/unpublish' => 'snippets#unpublish'
        put '/bookmark' => 'snippets#bookmark'
        put '/remove_bookmark' => 'snippets#remove_bookmark'
        put '/feature' => 'snippets#feature'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    resources :templates, except: :index do
      member do
        put '/publish' => 'templates#publish'
        put '/unpublish' => 'templates#unpublish'
      end
      resources :infopages, except: :index
    end
  end



  resources :categories, only: [:index, :show] do
    resources :tutorials, except: :index do
      resources :questions, shallow: true do
        resources :comments, except: :show do
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
        end
      end
      resources :infos, except: :index do
        resources :notes, shallow: true
      end
      member do
        put '/add_member' => 'tutorials#add_member'
        put '/remove_member' => 'tutorials#remove_member'
        put '/like', to: 'tutorials#like'
        put '/dislike', to: 'tutorials#dislike'
        put '/admin_remove_member', to: 'tutorials#admin_remove_member'
        put '/publish' => 'tutorials#publish'
        put '/unpublish' => 'tutorials#unpublish'
        get '/add_template' => 'tutorials#add_template'
        put '/add_this_template' => 'tutorials#add_this_template'
        put '/remove_template' => 'tutorials#remove_template'
        get '/payment' => 'tutorials#payment', as: 'payment'
        put '/buy' => 'tutorials#buy', as: 'buy'
        put '/quick_buy' => 'tutorials#quick_buy'
      end
    end
  end


  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :users, only: :show do
    resources :blogs
    member do
      put '/follow', to: 'users#follow'
      put '/unfollow', to: 'users#unfollow'
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: :new
  before_action :redirect_to_signup, only: :new

  def new
  end

  def create
    begin
      obj = CreateSubscriptions.new(current_user)
      customer = obj.find_or_register_user
      if params[:plan] == ""
        flash[:danger] = 'Please select a plan'
        redirect_to subscriptions_path and return
      end
      if current_user.subscribed?
        if customer.subscriptions.retrieve(current_user.stripe_subscription_id).plan.id == params[:plan].to_s
          flash[:danger] = 'You cannot subscribe to the same plan again'
          redirect_to subscriptions_path and return
        end
        customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
      end

      subscription = customer.subscriptions.create(
          source: params[:stripeToken],
          plan: params[:plan]
      )
      current_user.update(
          stripe_id: customer.id,
          stripe_subscription_id: subscription.id,
          card_last4: params[:card_last4],
          card_exp_month: params[:card_exp_month],
          card_exp_year: params[:card_exp_year],
          card_type: params[:card_type]
      )
      ahoy.track "Subscriptions", title: params[:plan].to_s
    rescue Stripe::CardError => e
      flash[:danger] = e.to_s
      redirect_to root_path and return
    end
    if current_user.save
      flash[:success] = 'Your subscription was successful !'
      redirect_to root_path
    end
  end

  def show

  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)
    flash[:success] = 'Your subscription has been canceled successfully'
    redirect_to root_path
  end

  private
  def redirect_to_signup
    if !user_signed_in?
      session['user_return_to'] = new_subscription_path
      redirect_to new_user_registration_path
    end
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def temp(&block)
    block.call if Rails.env.development?
  end

  #Gets current user and sends the subscription name
  # -> edit_user_registration_path
  def get_susbscription_name(user)
    customer = Stripe::Customer.retrieve(user.stripe_id)
    sub = customer.subscriptions.retrieve(user.stripe_subscription_id)
    sub.plan.name.to_s
  end
end

app/views/subscriptions/new.html.erb
<% ahoy.track 'Viewed Subscriptions form', track: 'Subscription' %>
<h1>Subscribe !</h1>
<script type="text/javascript" charset="utf-8">
  function getURLParameter(name) {
    return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null;
  }

</script>


<%= form_tag subscriptions_path, :id=> 'payment-form' do %>
<span class="payment-errors"></span>
    <script>$("input[name='plan']").val(getURLParameter('plan'));</script>
    <input type="hidden" name="plan" value="">

<div class="form-row">
  <label>
    <span>Card Number</span>
    <input value="4242424242424242" type="text" size="20" data-stripe="number"/>
  </label>
</div>

<div class="form-row">
  <label>
    <span>CVC</span>
    <input value="123" type="text" size="4" data-stripe="cvc"/>
  </label>
</div>

<div class="form-row">
  <label>
    <span>Expiration (MM/YYYY)</span>
    <input value="10" type="text" size="2" data-stripe="exp-month"/>
  </label>
  <span> / </span>
  <input value="2017" type="text" size="4" data-stripe="exp-year"/>
</div>

<button type="submit">Submit Payment</button>
<% end %>

app/views/subscriptions/show.html.erb
<% ahoy.track 'Viewed Subscriptions', track: 'Subscription' %>
<h2 class="text-center text-info">Subscriptions</h2>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4 class="text-center">Student</h4>
      </div>
      <div class="panel-body text-center">
        <p class="lead">
          <strong>$3 / month</strong>
        </p>
      </div>
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item">
          Create your own notes
        </li>
        <li class="list-group-item">
          Access to all help forums
        </li>
      </ul>
      <div class="panel-footer">
<%= link_to 'Subscribe', new_subscriptions_path(plan: 'monthly'), class: 'btn btn-lg btn-block btn-success' %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="text-center">Standard commercial package</h4>
      </div>
      <div class="panel-body text-center">
        <p class="lead">
          <strong>$10 / month</strong>
        </p>
      </div>
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item">
          Personal Use
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
        <li class="list-group-item">
          Single Commercial License
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
        <li class="list-group-item">
          Multiple site Commercial license
          <span class="glyphicon glyphicon-remove pull-right"></span>
        </li>
        <li class="list-group-item">
          Technical Support
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
      </ul>
      <div class="panel-footer">
        <%= link_to 'Subscribe', new_subscriptions_path(plan: 'entrepreneur'), class: 'btn btn-lg btn-block btn-info' %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4 class="text-center">Premium commercial package</h4>
      </div>
      <div class="panel-body text-center">
        <p class="lead">
          <strong>$20 / month</strong>
        </p>
      </div>
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item">
          Personal Use
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
        <li class="list-group-item">
          Single Commercial License
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
        <li class="list-group-item">
          Multiple site Commercial license
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
        <li class="list-group-item">
          Technical Support
          <span class="glyphicon glyphicon-ok pull-right"></span>
        </li>
      </ul>
      <div class="panel-footer">
        <a class="btn btn-lg btn-block btn-primary">Purchase</a>
      </div>
    </div>
  </div>
</div>