config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  resource :subscriptions
  resource :card
  resource :charges
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  namespace :admin do
    root 'dashboard#index'
    resources :categories, except: [:show]
    resources :dashboards, only: [:index]
    resources :users
  end

  namespace :creators do
    root 'dashboard#index'
    get '/category_information' => 'dashboard#category_information', as: 'information'
  end

  #Stripe WebHook
  mount StripeEvent::Engine, at: '/stripe/webhook'

  #Searchkick Search
  get '/search' => 'static#search', as: 'search'
  get '/autocomplete' => 'static#autocomplete', as: 'autocomplete'

  #Stripe authentication
  get '/connect/oauth' => 'connect#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'connect#confirm', as: 'stripe_confirm'

  resources :categories, only: [:index, :show] do
    resources :snippets do
      member do
        put '/like' => 'snippets#like'
        put '/dislike' => 'snippets#dislike'
        put '/publish' => 'snippets#publish'
        put '/unpublish' => 'snippets#unpublish'
        put '/bookmark' => 'snippets#bookmark'
        put '/remove_bookmark' => 'snippets#remove_bookmark'
        put '/feature' => 'snippets#feature'
      end
    end
  end

  resources :categories, only: [:index, :show] do
    resources :templates, except: :index do
      member do
        put '/publish' => 'templates#publish'
        put '/unpublish' => 'templates#unpublish'
      end
      resources :infopages, except: :index
    end
  end



  resources :categories, only: [:index, :show] do
    resources :tutorials, except: :index do
      resources :questions, shallow: true do
        resources :comments, except: :show do
          post '/upvote' => 'comments#upvote'
          post '/downvote' => 'comments#downvote'
        end
      end
      resources :infos, except: :index do
        resources :notes, shallow: true
      end
      member do
        put '/add_member' => 'tutorials#add_member'
        put '/remove_member' => 'tutorials#remove_member'
        put '/like', to: 'tutorials#like'
        put '/dislike', to: 'tutorials#dislike'
        put '/admin_remove_member', to: 'tutorials#admin_remove_member'
        put '/publish' => 'tutorials#publish'
        put '/unpublish' => 'tutorials#unpublish'
        get '/add_template' => 'tutorials#add_template'
        put '/add_this_template' => 'tutorials#add_this_template'
        put '/remove_template' => 'tutorials#remove_template'
        get '/payment' => 'tutorials#payment', as: 'payment'
        put '/buy' => 'tutorials#buy', as: 'buy'
        put '/quick_buy' => 'tutorials#quick_buy'
      end
    end
  end


  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', omniauth_callbacks: 'callbacks' }
  resources :users, only: :show do
    resources :blogs
    member do
      put '/follow', to: 'users#follow'
      put '/unfollow', to: 'users#unfollow'
    end
  end
end

app/models/info.rb
# == Schema Information
#
# Table name: infos
#
#  id          :integer          not null, primary key
#  title       :string
#  content     :text
#  tutorial_id :integer
#  category_id :integer
#  slug        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Info < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  searchkick text_start: ['title^10',:content], batch_size: 100


  belongs_to :tutorial
  belongs_to :category
  has_many :notes, dependent: :destroy

  validates :title, :content, presence: true


  def slug_candidates
    [
        :title,
        [:id, :title]
    ]
  end

end

app/controllers/infos_controller.rb
# == Schema Information
#
# Table name: infos
#
#  id          :integer          not null, primary key
#  title       :string
#  content     :text
#  tutorial_id :integer
#  category_id :integer
#  slug        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class InfosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_category
  before_action :set_tutorial
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  def new
    @info = @tutorial.infos.new
    authorize @info, :create?
  end

  def create
    @info = @tutorial.infos.create(info_params)
    authorize @info, :create?
    if @info.save
      flash[:success] = 'Page was successfully created'
      redirect_to category_tutorial_info_path(@category, @tutorial, @info)
    else
      flash.now[:danger] = 'Page was not created'
      render :new
    end
  end

  def show
    if @tutorial.price > 0
      authenticate_user!
      if !current_user.purchases.exists?(tutorial_id: @tutorial.id)
        flash[:warning] = 'You need to purchase the tutorial to view the pages'
        redirect_to [@category, @tutorial] and return
      end
    end
    authorize @info, :show?
    @notes = @info.notes.where(user: current_user).order('created_at DESC')
  end

  def edit
    authorize @info, :update?
  end

  def update
    authorize @info, :update?
    if @info.update(info_params)
      flash[:success] = 'Page was successfully updated'
      redirect_to category_tutorial_info_path(@category, @tutorial, @info)
    else
      flash.now[:danger] = 'Page was not updated'
      render :edit
    end
  end

  def destroy
    authorize @info, :destroy?
    @info.destroy
    flash[:success] = 'Page was successfully deleted'
    redirect_to category_path(@category)
  end

  private

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

  def set_tutorial
    @tutorial = @category.tutorials.friendly.find(params[:tutorial_id])
  end

  def set_info
    begin
      @info = @tutorial.infos.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:danger] = 'The page you searched for could not be found'
      redirect_to root_path
    end
  end

  def info_params
    params.require(:info).permit(:title, :content)
  end
end

app/views/infos/_form.html.erb
<%= simple_form_for [@category, @tutorial, @info] do |f| %>
    <%= f.input :title, required: true, autofocus: true %>
    <%= f.input :content, class: 'summernote' %>
    <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/infos/edit.html.erb
<h2>Edit Page</h2>
<%= render 'form' %>

app/views/infos/new.html.erb
<h1>New Page</h1>
<%= render 'form' %>

app/views/infos/show.html.erb
<% ahoy.track 'Viewed Info', track: @info.title %>

<% if policy(@info).update? %>
    <%= link_to 'Edit this page', edit_category_tutorial_info_path(@category, @tutorial, @info),
                class: 'btn btn-success' %>
<% end %>
<% if policy(@info).destroy? %>
    <%= link_to 'Delete this page', category_tutorial_info_path(@category, @tutorial, @info),
                method: :delete, data: {confirm: 'Are you sure you want to delete this page ?'}%>
<% end %>

<%= @info.title %>
<%= @info.content.html_safe %>
<hr>
<% if user_signed_in? %>
    <h2 class="text-center">My Notes</h2>
    <% @notes.each do |note| %>
        <div class="well" id="<%= "note_#{note.id}" %>">
          <%= link_to note.title, note_path(note), remote: true %>
          <%= link_to 'Edit', edit_note_path(note), class: 'btn btn-primary btn-xs', remote: true %>
          <%= link_to 'Delete Note', note_path(note), method: :delete, data: { confirm: 'Are you sure ?'}, class: 'btn btn-danger btn-xs', remote: true %>
        </div>
    <% end %>

    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#newNote">
      Create a note
    </button>
    <div id="modal_body"></div>
<% end %>

<!-- Modal -->
<%= render partial: 'notes/form', locals: { category: @category, tutorial: @tutorial, info: @info } %>